### ISSUE TITLE
state of the client

### ISSUE THREAD

**Issue by tbarbugli** [shawnspeak/stream-net#1]
Hi there,
I am Tommaso CTO of getstream.io. Awesome that you built a .net API client! Are you already using the client on your application? Feel free to ping on tommaso@getstream.io to talk about the client ;)

**Comment by shawnspeak** [comment]
I am currently using the client on two different projects.. one of which will be putting the client library into production soon.

getstream.io is a great solution for a number of problems I keep encountering.. only issue for me was that it needed a .Net client... so now we have one :)

**Comment by tbarbugli** [comment]
I like to hear that! The client looks really neat, great work! I am going to link your project in our documentation page in the coming days :) I would love to hear more about what you are building, perhaps email is better for the kind of conversation?

**Comment by tschellenbach** [comment]
Hi there,

Thierry here from Stream. We'd like to sponsor a bit of work on the .NET client to make sure it's feature complete. Do you think you could help us out with a small freelance job to take the .NET client to the next level? My email is on my Github profile.

Cheers,
Thierry
