### ISSUE TITLE
ASP.NET 5 / ASP.NET Core 1.0

### ISSUE THREAD

**Issue by rosenbergp** [shawnspeak/stream-net#10]
Shawn,

Hope your doing well.

Question:

Are there plans to make stream-net ASP.NET Core 1.0 compatible?

**Comment by shawnspeak** [comment]
No specific plans yet, but I anticipate needing the compatibility this year sometime.

**Comment by rosenbergp** [comment]
Any ETA on getting the stream-net ASP.NET Core 1.0 compatible?

If you need help, I have converted a 12 class libraries into ASP.NET Core 1.0 packages. I have more experience since February. Let me know.

**Comment by Sampath-Lokuge** [comment]
Hi @shawnspeak 

Is this compatible with Asp.net Core 1.X now ? Thanks.

**Comment by shawnspeak** [comment]
I've added a new branch called dotnetcore that builds against .Net core. Still working on getting the tests to run properly, but should have this merged into master soon.

**Comment by Amila17** [comment]
@shawnspeak Hi Shawn, any update on this?

**Comment by shawnspeak** [comment]
Project has (finally) been updated to support .Net Core. Nuget package has been updated
