### ISSUE TITLE
Unable to get custom fields.

### ISSUE THREAD

**Issue by abhijit838** [shawnspeak/stream-net#19]
Able to add custom fields value to api, but unable to get custom fields value from api. I am very new getstream, is there any doc that can help me. Is this available in paid version?

**Comment by abhijit838** [comment]
All extra parameters are coming but after calling GetData explicitly. Custom parameters are not automatically coming as separate json parameters in response.results

**Comment by shawnspeak** [comment]
Take a look at the following test case [https://github.com/shawnspeak/stream-net/blob/master/src/stream-net-tests/IntegrationTests.cs#L186](https://github.com/shawnspeak/stream-net/blob/master/src/stream-net-tests/IntegrationTests.cs#L186) which has examples of using custom fields of various types.

**Comment by abhijit838** [comment]
Got it, Always i have to do GetData
