### ISSUE TITLE
Switch to new Api endpoints

### ISSUE THREAD

**Issue by TylerFinagraph** [shawnspeak/stream-net#23]
GetStream recommends switching api clients to their new endpoints:

```
https://us-east-api.stream-io-api.com/api/v1.0/

https://us-west-api.stream-io-api.com/api/v1.0/

https://eu-central-api.stream-io-api.com/api/v1.0/ 
```

https://getstream.io/blog/stop-using-io-domain-names-for-production-traffic/

Any chance we could do this? Or are you accepting PRs?

**Comment by shawnspeak** [comment]
Changing them now and getting the nuget package updated

**Comment by shawnspeak** [comment]
The nuget package has been updated.
