### ISSUE TITLE
JsonSerializationException when getting following feeds

### ISSUE THREAD

**Issue by TylerFinagraph** [shawnspeak/stream-net#25]
When calling StreamFeed.Following with no parameters, I'm getting the following exception:

```
Newtonsoft.Json.JsonSerializationException: 'Error converting value {null} to type 'System.DateTime'. Path 'results[0].updated_at', line 1, position 232.'
```

Looking at the response from GetStream, it looks like updated_at is null:

```
{
 "feed_id": "user:aggregate-dev-2942a2fa-fa7a-46b1-b11a-229ee95f8818-aggregate2",
 "target_id": "user:c1de77da-b521-4af6-9589-7498c66b163d",
 "created_at": "2017-12-12T19:57:49.768087Z",
 "updated_at": null
}
```

This same code seemed to work not long ago (a month maybe?).  Do you know if something in the GetStream api changed recently?

**Comment by shawnspeak** [comment]
None that I'm aware of beyond the API endpoint changes.

The odd thing is I just ran the integration tests that cover this call and they pass. Digging a bit deeper, my responses all contain an "updated_at" value.

@tbarbugli might be able to help us with this.

**Comment by TylerFinagraph** [comment]
Any updates on this? Errors are still appearing. I would think we need to update UpdatedAt to be a nullable DateTime.

**Comment by stilldavid** [comment]
The `updated_at` field can safely be ignored as it's not really meaningful. There was a recent change such that the field is no longer getting populated at follow creation, which is causing this breakage. We'll change the API response to return the `created_at` value in `updated_at` in the coming week, but the more correct thing to do would be to update this integration to ignore the field.

**Comment by shawnspeak** [comment]
Thanks for the info @stilldavid .. I'll make the changes

**Comment by shawnspeak** [comment]
I've updated the code and nuget package to ignore the UpdatedAt value. I left the property in place but have marked it Obsolete and will remove it in the future.

**Comment by reddy6ue** [comment]
Close this if release made?
