### ISSUE TITLE
Not disposing HttpClient, making it static.

### ISSUE THREAD

**Issue by mennolaan** [shawnspeak/stream-net#26]
With the recent articles regarding the state of HttpClient and abusing disposable on it, I was taking a look at the source. I would like to suggest to implement a static reference for the HttpClient combined with the lazy property. With stream-net always having the same base address, no modifications for the headers it seems to me this is a perfect situation where not to dispose the HttpClient in order to improve performance of socket reuse. Now that I moved al the stream-net calls to azure functions I like to limit the duration times of said functions. Recreating the HttpClientis very time consuming and performance suffers from this.

I would be happy to add a pull request if you're open to it.

Ref:
https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/
https://contrivedexample.com/2017/07/01/using-httpclient-as-it-was-intended-because-youre-not/

Edit, just noticed ServicePointManager.FindServicePoint(GetBaseUrl()).ConnectionLeaseTimeout =is not possible in .NetCore. According to https://github.com/dotnet/corefx/issues/11224 solution could be refreshing the client every hour in case a DNS change has happened, as shown in the url.

**Comment by shawnspeak** [comment]
Thanks for the pointing this out. 

I don't think it's a good idea for any library to hold a static reference that cannot be disposed should it's users wish to do so. Given that, what if we extend StreamClient to be IDisposable and then hold a single reference to the HttpClient there? That way you could keep a static reference around (via StreamClient) should you wish to or dispose if needed. Thoughts?

**Comment by shawnspeak** [comment]
I've added a new branch [disposable](https://github.com/shawnspeak/stream-net/tree/disposable) that changes StreamClient to hold a reference to HttpClient via the RestClient class. Take a look and let me know what you think.

**Comment by mennolaan** [comment]
Thanks Shawn, I'll have a look!

**Comment by mennolaan** [comment]
Reporting back, was kind of busy this week. Anyway for .net 4.6.1 I have a solution, .net core needs some extra work.. 

In short 30 to 50 % performance increase and no more socket exhaustian, wich is a greater concern with disposing the httpclient in high volume environments. After running this example check CMD prompt(with admin rights) netstat -abn. You will see a lot of connections open (time_wait).

Now I have implemented this with my azure functions. The performance gain is roughly the same as with this test.

Please note, code is a bit sloppy as I wanted to see the results, made some modifications on your code as well to move the httpclient to a static class.

https://github.com/mennolaan/StreamNetPerformanceTest/tree/master

**Comment by shawnspeak** [comment]
Thanks for working on this.

My only concern with your modifications is that there is no way to dispose of HttpClient should someone wish to do so. If StreamClient is disposed, everything it instantiates must be disposed. We should be able to address all of the performance issues without having a static HttpClient in the library.

I'll work with your test cases and see what I can come up with.

**Comment by mennolaan** [comment]
You're completely right, this isn't a production ready code. I did remove the dispose function on purpose for the test environment but like you said this isn't something you want to lock down in a package. Obviously I'll be looking into some more documentation to see if this solution could be more generic and also support al the .net dependencies such as net-standard / core.

**Comment by reddy6ue** [comment]
@shawnspeak Why don't we inject the HttpClient? 
That way, we can use DI to manage the HttpClient lifecycle.

**Comment by shawnspeak** [comment]
@reddy6ue It is something to consider. The big issue I see is that we expose the whole library to failure if the user were to make changes to that external HttpClient reference.. such as changing the Timeout or adding/removing DefaultHeaders. And while this would allow the user to control the lifecycle of HttpClient it also then forces the user to control the lifecycle (unless we provide various constructors). 

Personally I like REST API libraries to handle these kinds of things for me and not make me deal with the mechanics of HTTP, networking, etc.

**Comment by k-ljung** [comment]
Good news for .NET Core 2.1, https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore

**Comment by reddy6ue** [comment]
@k-ljung Hallelujah!!
