### ISSUE TITLE
Using AddAcitivity with .NET

### ISSUE THREAD

**Issue by elitepacific-alex** [shawnspeak/stream-net#28]
Hi!

Can you enlighten me with working with AddActivity please? I'm using VB and would like to know how can include other data like "tweet" and all other contents. 

Thanks in advance!

```
Dim actlike = New Activity("Alex", "comment", "post:4b93b75c-378e-11e8-9926-128899f22c76") With {
            .ForeignId = "comment:2979ad56-377e-11e8-9696-0ad650757e1c",
            .Time = Now.ToUniversalTime,
            .To = {"notification:eric"}
        }
```

**Comment by shawnspeak** [comment]
The following will added custom content to an activity:

`actlike.SetData("tweet","tweet value")`

**Comment by elitepacific-alex** [comment]
That definitely works! Thank you!

**Comment by reddy6ue** [comment]
@shawnspeak Consider closing this?
