### ISSUE TITLE
Anyone use within Unity Editor?

### ISSUE THREAD

**Issue by jlankitus** [shawnspeak/stream-net#30]
Hello, wondering if anyone has tried using this in Unity Editor and knows how to make it work. I got the code to compile, but has a runtime error within Unity

**Comment by reddy6ue** [comment]
You may want to post the error here. There's nothing in StreamClient that's specific to Unity. You're most likely configuring Unity incorrectly. 

I have used StreamClient with Autofac and I've had no problems making it work.
