### ISSUE TITLE
Activities for Video and Images

### ISSUE THREAD

**Issue by rosenbergp** [shawnspeak/stream-net#5]
Hi Shawn,

Great stuff with your steam-net client.

Hope your having a great day.

Couple questions:

Activities with non YouTube videos:

To do an activity and share a video that is not on YouTube, using yourstream-net client.

GetStreamIo has the following example posted for sharing YouTube videos:

addActivity({actor: 'eric', verb: 'watch', object: 1, youtube_id: 'z_AbfPXTKms'}

But what if the video is not on YouTube and say the video resides some where else. What if we want that activity to show an image of the video but have the image link to the video url.

How would add that activity using your stream-net client?

Activities with sharing pictures:

We want to do an activity that shares a picture, using stream-net client.

How do we do that?

Thank you for your time in reading this message and the time it takes to create the detailed response.

Have a great day and great weekend.

Regards,

Patrick Rosenberg

**Comment by shawnspeak** [comment]
Hey Patrick, 

In general, one would use the `object` property of an activity to identify what the `verb` is acting on. So in your case, your object could be something like `video:1234566` with your verb being `watch`. Then when read the activity back into your application you can convert the `video:1234566` into urls that reference the video and image endpoints.

Alternatively, you could use "extra" data on an activity with the following code:

```
var activity = new Activity("eric", "watch", "1");
activity.SetData("videoUrl", "http://somwhere.else.com/video_id")
activity.SetData("imageUrl", "http://somwhere.else.com/img_id")
someFeed.AddActivity(activity);
```

And then retrieve the data later:

```
var videoUrl = activity.GetData<String>("videoUrl")
```

Does that help?

shawn

**Comment by rosenbergp** [comment]
That does help, thank you.

But say we wanted to show a image of the video in the post, or an image of the picture.

We would have to create html and SetData would than be our html, correct?

You stated: 
"one would use the object property of an activity to identify what the verb is acting on. So in your case, your object could be something like video:1234566 with your verb being watch. Then when read the activity back into your application you can convert the video:1234566 into urls that reference the video and image endpoints."

Can you show me a quick syntax example of the above?

I am new to this stuff, so seeing it written out helps me out  a lot.

Thank you again for your time.

**Comment by shawnspeak** [comment]
I would not use SetData to store the HTML along with the activity as your HTML structure will most likely change over time. Better to build the HTML as you render the page.

To create an activity as I suggested:

```
var activity = new Activity("user:eric", "watched", "video:123566");
someFeed.addActivity(activity); 
```

Then get the activity and convert the object id to a url:

```
var activities = someFeed.GetActivities();
foreach (var activity in activites)
{
    var objId = activity.Object.Split(':');
    if (objId[0] == "video")
    {
        var videoUrl = String.Format("http://somewhere.com/videos/{0}", objId[1]);
        var imageUrl = String.Format("http://somewhere.com/images/{0}", objId[1]);

        // store the urls in a view model (for MVC) or output on the page for ASPX 
    }
}
```

**Comment by rosenbergp** [comment]
Thanks Shawn!

That makes sense and helps me out  a lot.

Have a great rest of your week!

Regards,

Patrick
